site_name: Python Freezable Docs
repo_url: https://github.com/ederic-oytas/python-freezable
repo_name: ederic-oytas/python-freezable
site_description: Documentation for the `freezable` Python package.
site_author: Ederic Oytas

theme:
  name: "material"
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
  - search

nav:
  - Home: index.md
  - User Guide: user-guide.md
  - Reference: reference.md
  - Roadmap: roadmap.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

watch:
  - freezable
